version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - showMeScraper/backend/.env
    ports:
      - "5432:5432"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    restart: unless-stopped
  server:
    build:
      context: ./showMeScraper/backend
      dockerfile: Dockerfile
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file:
      - showMeScraper/backend/.env
    ports:
      - 8000:8000
volumes:
    postgres_data:
